name: Sync

on:
  workflow_dispatch:

jobs:
  run-sync:
    uses: gucio1200/gh-workflows/.github/workflows/general_sync.yml@main
    with:
      source_repo_url: "https://github.com/terraform-linters/tflint-ruleset-azurerm.git"
      dry_run: false
    secrets: inherit
